services:
  app:
    build: .
    container_name: drdr-backend
    ports:
      - "8000:8000"
    networks:
      - dorandoran

networks:
  dorandoran:
    driver: bridge
    ### TODO
    # name 옵션 붙이기
    # npm 설정